AWSTemplateFormatVersion: "2010-09-09"
Description: "A simple Ubuntu 16.04 server"
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0417e362"
      InstanceType: "t2.nano"
      KeyName: "gslin"
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sdm"
          Ebs:
            VolumeType: "gp2"
            DeleteOnTermination: "true"
            VolumeSize: "8"
